### ISSUE TITLE
App UI layout messed for certain apps

### ISSUE THREAD

**Issue by dallasgroot** [ioscreatix/LittleX#2]
[pic](https://twitter.com/iamgroot11/status/966903897297100801)

Basically from the title. This also effects maps in CarPlay (I’ll upload a pic of this as well)

I’ve disabled LittleX dylib from loading to pinpoint the issue and it definitely is the tweak causing this. 

iPhone 8 (GSM) 11.1.2 LittleX 1.3.4

**Comment by andrewwiik** [comment]
So disable LittleX for these apps

**Comment by dallasgroot** [comment]
This actually didn’t solve anything when disabling app by app, but it appears the latest update fixed the issue.
