### ISSUE TITLE
All the apps crash when you type fast.

### ISSUE THREAD

**Issue by Isaac7u7** [ioscreatix/LittleX#28]
Some apps when I type, it issue happens sometimes on the day. I dont want to disable littleX on this apps beacuse on this case i would have to disable  on all apps that requires write.
Even try to disable larger keyboard and it somehow reduces the crash but still happening
Please, help me to fix :(

**Comment by Quoll-io** [comment]
Due to a lack of CrashReporter, crash bugs will currently be ignored. The moment crash reporter is updated please reopen this issue with included crash reports.

Thank you!
