### ISSUE TITLE
LittleX crashes springboard

### ISSUE THREAD

**Issue by tryfontheo** [ioscreatix/LittleX#38]
I installed LittleX on my iP6 on 11.0 and it just immediately crashes springboard. Fluidity and Home Gestures do not work as well for some reason. I can post a log but I am not sure where they are stored

**Comment by Quoll-io** [comment]
Due to a lack of CrashReporter, crash bugs will currently be ignored. The moment crash reporter is updated please reopen this issue with included crash reports.

Thank you!
