### ISSUE TITLE
Swiping down for the control center the moment after opening an app crashes to safemode

### ISSUE THREAD

**Issue by mattp12** [ioscreatix/LittleX#7]
iPhone 6, running release Electra 1.0.2.

This has been happening for as long as LittleX (or tweaks like Fluidity/Fluidenabler) has been around, as far as I know.

**Comment by Quoll-io** [comment]
Due to a lack of CrashReporter, crash bugs will currently be ignored. The moment crash reporter is updated please reopen this issue with included crash reports.

Thank you!
